In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = 'https://www.transfermarkt.com/premier-league/ewigeTabelle/pokalwettbewerb/GB1'
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

page = requests.get(url, headers = headers)
soup = BeautifulSoup(page.text, 'html')

In [3]:
table = soup.find("table", class_='items')

In [4]:
header = table.find_all("a", class_="sort-link")

In [5]:
titles = [] 
for h in header:
    head = h.text
    titles.append(head)

In [6]:
club_header = table.find('th', id="yw1_c0")

In [7]:
club_name = table.find('th', id="yw1_c2")

In [8]:
titles.insert(0, club_header.text)
titles.insert(1, club_name.text)
empty = 'empty'
titles.insert(1, empty)

In [9]:
titles

['#', 'empty', 'Club', 'Matches', 'W', 'D', 'L', 'GD', 'Points']

In [10]:
df = pd.DataFrame(columns = titles)

In [11]:
rows = table.find_all('tr')
row = []

In [12]:
for r in rows[1:]:
    data = r.find_all('td')
    row = [tr.text for tr in data]
   
    l = len(df)
    df.loc[l]= row

In [13]:
df = df.drop('empty', axis = 1)
df = df.rename(columns={'#': 'Rank'})
df

   Rank                     Club Matches    W    D    L     GD Points
0     1        Manchester United   1.210  736  264  210  1.129  2.472
1     2               Arsenal FC   1.210  657  294  259    931  2.265
2     3             Liverpool FC   1.210  641  298  271    927  2.221
3     4               Chelsea FC   1.210  637  299  274    842  2.210
4     5        Tottenham Hotspur   1.210  532  290  388    327  1.886
5     6          Manchester City   1.019  513  219  287    675  1.758
6     7               Everton FC   1.210  434  334  442    -17  1.626
7     8         Newcastle United   1.092  410  280  402      5  1.510
8     9              Aston Villa   1.096  385  306  405    -67  1.461
9    10          West Ham United   1.054  356  264  434   -204  1.332
10   11           Southampton FC     924  280  248  396   -241  1.088
11   12         Blackburn Rovers     696  262  184  250     20    970
12   13           Leicester City     650  218  167  265    -65    821
13   14             Leeds United     582  223  151  208      9    820
14   15                Fulham FC     628  184  164  280   -205    716
15   16         Middlesbrough FC     574  165  169  240   -146    661
16   17           Crystal Palace     560  161  147  252   -195    630
17   18           Sunderland AFC     608  153  159  296   -292    618
18   19         Bolton Wanderers     494  149  128  217   -170    575
19   20     West Bromwich Albion     494  117  139  238   -262    490
20   21               Stoke City     380  116  109  155   -127    457
21   22  Wolverhampton Wanderers     362  109   90  163   -162    417
22   23            Coventry City     354   99  112  143   -103    409
23   24             Norwich City     392   99  105  188   -255    402
24   25      Sheffield Wednesday     316  101   89  126    -44    392
25   26    Wimbledon FC (- 2004)     300   96   86  118    -82    374
26   27        Charlton Athletic     304   93   82  129   -100    361
27   28               Burnley FC     324   86   78  160   -176    336
28   29           Wigan Athletic     304   85   76  143   -166    331
29   30             Swansea City     266   82   66  118    -77    312
30   31      Queens Park Rangers     278   81   65  132    -92    308
31   32   Brighton & Hove Albion     248   74   80   94    -44    302
32   33          Birmingham City     266   73   82  111    -87    301
33   34        Nottingham Forest     256   74   75  107    -99    297
34   35            Portsmouth FC     266   79   65  122    -88    293
35   36               Watford FC     304   73   66  165   -208    285
36   37          AFC Bournemouth     247   74   53  120   -130    275
37   38             Derby County     266   68   70  128   -149    274
38   39             Ipswich Town     202   57   53   92    -93    224
39   40         Sheffield United     218   55   53  110   -117    218
40   41                Hull City     190   41   48  101   -142    171
41   42             Brentford FC      95   33   25   37     -1    124
42   43               Reading FC     114   32   23   59    -50    119
43   44          Oldham Athletic      84   22   23   39    -37     89
44   45             Cardiff City      76   17   13   46    -77     64
45   46            Bradford City      76   14   20   42    -70     62
46   47        Huddersfield Town      76   12   17   47    -84     53
47   48             Blackpool FC      38   10    9   19    -23     39
48   49              Barnsley FC      38   10    5   23    -45     35
49   50             Swindon Town      42    5   15   22    -53     30
50   51               Luton Town      19    4    3   12    -14     15

In [14]:
df.to_csv('epl.csv')